### ISSUE TITLE
Multiple windows open and can't locate game

### ISSUE THREAD

**Issue by asimard1** [fifty-six/Scarab#103]
### Scarab Version

v1.19.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

1. Install scarab and mods, open and play the game.
2. Close game.
3. Open scarab, disable API.
4. Open game and play.
5. Close game.
6. Open scarab.
7. Try to enable API.

However, there were some times where these steps did not cause any problems. It caused them after a couple times.

### Expected Behaviour

Scarab opens one window and be able to enable/disable API as wished.

### Actual Behaviour

Multiple windows opened for Scarab, and the program is now unable to locate my game (even when the folder specified is the right one). The game goes to a black screen when launched. Scarab window is sometimes empty.

![image](https://user-images.githubusercontent.com/58919185/183311045-5923dd55-f026-4a10-a3a2-9c8798992c71.png)

(The path selected is the one with Hollow Knight in it.)

![image](https://user-images.githubusercontent.com/58919185/183311078-9894ccd5-d802-47ae-bc9d-ca7240f760a7.png)

### Logs

I'll send all the files of interest, just in case there are more details.

[ModInstaller.log](https://github.com/fifty-six/Scarab/files/9277570/ModInstaller.log)
[1160e9d3-e443-4996-8f6b-e32c9a9a1453ModInstaller.log](https://github.com/fifty-six/Scarab/files/9277572/1160e9d3-e443-4996-8f6b-e32c9a9a1453ModInstaller.log)
[379a2f82-1663-44f2-90b8-d8a8c90ffed7ModInstaller.log](https://github.com/fifty-six/Scarab/files/9277573/379a2f82-1663-44f2-90b8-d8a8c90ffed7ModInstaller.log)
[927c7a78-0335-465a-87c1-1e0104590c1cModInstaller.log](https://github.com/fifty-six/Scarab/files/9277574/927c7a78-0335-465a-87c1-1e0104590c1cModInstaller.log)
[ModInstaller_Error_22-08-07 16-38-57.log](https://github.com/fifty-six/Scarab/files/9277577/ModInstaller_Error_22-08-07.16-38-57.log)

**Comment by asimard1** [comment]
Additionnal file.

[ModInstaller_Error_22-08-07 16-38-57.log](https://github.com/fifty-six/Scarab/files/9277590/ModInstaller_Error_22-08-07.16-38-57.log)

**Comment by asimard1** [comment]
Verified game files, which made the game run again (without mods of course). Delete scarab folder (with executable) and HKModInstaller folder in %appdata%, reinstalled, and it seems to be back to normal.

I will try to recreate the behavior if needed.

**Comment by asimard1** [comment]
I've tried disabling and enabling the modding API a couple times (and opening the game between each) and it doesn't recreate the problem. It might come from having two HK installations. I had one from Game Pass and from Steam, and used Scarab with both. Deleted the one from Game Pass, so that might be the solution.

**Comment by asimard1** [comment]
Another file of interest, happened when I had a black screen while launching the game.

[ModLog.txt](https://github.com/fifty-six/Scarab/files/9277709/ModLog.txt)

**Comment by fifty-six** [comment]
The black screen is almost definitely from Custom Knight, it's throwing due to a lack of textures while using something that most of the game relies on. 


There's a bunch of errors regarding Game Pass earlier though, it can't be used without administrator access or copying the game to a different spot due to file permissions, though I've seen people still have issues with the former approach. Given you have the Steam one I'd recommend using it only with that one generally. If you didn't open it every time with admin that might fuck with it, might be corrupted settings from it failing in the middle and not me entirely handling it appropriately. Not entirely sure if I should leave this open or close it as a result, probably want to implement a massive warning or error for game pass earlier anyways.

**Comment by asimard1** [comment]
I think it's okay to close it, I will use only Steam from now on and everything works now.
