### ISSUE TITLE
when trying to download a mod, scarab tells that the game is open, which is not true

### ISSUE THREAD

**Issue by PedroStart2** [fifty-six/Scarab#126]
### Scarab Version

v1.19.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Uninstall hollow knight while mods are in the hk folder (uninstalled because the mods werent working

### Expected Behaviour

the game work again, and the mods too

### Actual Behaviour

only the vanilla game worked

### Logs

there isnt any logs on those folders

**Comment by fifty-six** [comment]
What happens if you hit `Yes`? This should trigger if you have any programs open that start with `hollow_knight` or `Hollow Knight` ([src](https://github.com/fifty-six/Scarab/blob/b01d25e6d938af396f308f4b0e60ed3c8283697d/Scarab/ViewModels/ModListViewModel.cs#L183)). Do you have anything similarly named? Is this on Windows? The logs (HKModinstaller.log being the main one) are in `%appdata%\HKModInstaller` if so.

**Comment by PedroStart2** [comment]
There arent any programs with the same name as Hollow Knight, and its on Windows 11.
If we hit 'Yes', scarab closes and if we try again the same happens.

**Comment by fifty-six** [comment]
Could I have the logs? If it closes it should be a crash of some sort

**Comment by fifty-six** [comment]
Oh yeah, added something that *should* fix this, but feel free to re-open if it doesn't.
