### ISSUE TITLE
RCPathfinder does not appear

### ISSUE THREAD

**Issue by flibber-hk** [fifty-six/Scarab#136]
### Scarab Version

1.20

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Open Scarab and look for RCPathfinder

### Expected Behaviour

It to appear

### Actual Behaviour

It did not appear

### Logs

It seems the issue is that RCPathfinder appears in https://cdn.jsdelivr.net/gh/hk-modding/modlinks@main/ModLinks.xml but does not appear in https://cdn.jsdelivr.net/gh/hk-modding/modlinks@latest/ModLinks.xml (at the time of writing, it is at the bottom of the xml in the file.

Side note - at the time of writing, <https://raw.githubusercontent.com/hk-modding/modlinks/main/ModLinks.xml> correctly has RCPathfinder appear; I'm not sure why it's falling back to the jsdelivr link.

Apparently there was a reason for using latest instead of main <https://github.com/fifty-six/Scarab/commit/5ba3de2a4b218f3ab4fbadb0efac0398275aea30>

**Comment by flibber-hk** [comment]
It's possible that this issue will resolve itself by the time you get a chance to investigate, but I hope I've provided enough information. (This https://github.com/hk-modding/modlinks/commit/7d5cc47760b4d8139fc0fde2ba695a1cfd7477d2 is the update that added RCPathfinder)

**Comment by fifty-six** [comment]
Branches (`@main`) take 12 hours as opposed to semver (includes `@latest`) which takes 7 days. It falls back to `jsdelivr` if it can't fetch the github link w/in 3 seconds, which is a fallback due to it being blocked/significantly faster in certain locations. There's a [cache purging system](https://www.jsdelivr.com/documentation#id-purge-cache) that I wanted to set up but I never asked for permissions - which they grant if you ask for a certain email.

**Comment by flibber-hk** [comment]
If main takes less time, what is the rationale for getting from latest?

**Comment by fifty-six** [comment]
The plan was to set up the caching thing, which only works on valid semver versions. `main` is a branch and thus not a semver version. Also, ideally you shouldn't have this issue anyways given you can access github
