### ISSUE TITLE
Scarab just doesn't load my mods after i had to revalidate my files

### ISSUE THREAD

**Issue by Maryoman** [fifty-six/Scarab#193]
### Scarab Version

2.3.0.0

### Hollow Knight Version

1.5.78.11833

### Steps to Reproduce

I just open it and no mods load, it boots normally. 
I'd assume its because of me revalidating some files and scarab not liking that

### Expected Behaviour

It loads mods

### Actual Behaviour

Normal boot

### Logs

[ModInstaller-20230929.log](https://github.com/fifty-six/Scarab/files/12773468/ModInstaller-20230929.log)

**Comment by fifty-six** [comment]
Do you mean that when you boot Hollow Knight, no mods get loaded?

**Comment by Maryoman** [comment]
yes

**Comment by chickenboi-09** [comment]
same issue here, i thought i might've had the api disabled or something and so i tried pressing the disable api button thinking i might've accidentally clicked it but when i tried to load the game after that the screen was black and it wouldn't go back to normal until i re-installed the game

**Comment by ShoebiII** [comment]
I also have this issue, however when I reinstall scarab after manually selecting the install path, the game won't open anymore. Until I verify the integrity of the game files, after which the mods still don't work.

**Comment by fifty-six** [comment]
So, re-validating your files is going to overwrite the API install - but Scarab doesn't "notice" this, so it won't reinstall the API by itself. I can add something to detect this at this point - I was avoiding it because I didn't want to have a hash in, but at this point this seems like the last patch so it's not a huge deal. I can also add a "Reinstall API" button/warning in the next version which would resolve this.

**Comment by fifty-six** [comment]
2.4.0.0 has a button for this now!
