### ISSUE TITLE
Scarab does not validate whether Hollow Knight or mods are still installed

### ISSUE THREAD

**Issue by powerlord** [fifty-six/Scarab#55]
I was having issues with my Hollow Knight install, so I uninstalled it and deleted its entire directory afterwards before reinstalling.

Scarab didn't pick up that the mods directory no longer existed, instead relying on a cache file in `%APPDATA%\HKModInstaller`.

**Comment by fifty-six** [comment]
Are you using the most recent version? It checks for the existence of the directory that it has stored, though not the Mods folder specifically as users who just opened it won't have that yet. Or did you reinstall Hollow Knight entirely and then relaunch it?

**Comment by JustBashka** [comment]
Hi, I'm having the same problem. I have re-downloaded the newest release (v.1.11.0.0, Linux version), entered the correct path, tried to enter it again through the Change Path button, but Scarab doesn't register that a number of mods is already installed (and working). Clicking Open Mods button opens the correct folder and I can see the mods in the folder just fine. 

I had this problem before getting the newest version and I had tried installing a new mod while Scarab showed no installed mods, and the new mod installed fine. Afterwards Scarab showed just this newest mod installed. Now with the newest release I can see no mods installed in Scarab.

**Comment by fifty-six** [comment]
The already installed mods don't get registered when you change paths as the mods are per-instance instead of detecting the existing files, I should probably clarify that and ask about clearing old ones. Adding a new mod and it disappearing without changing paths is an issue though, is that mod still in the folder and all?

**Comment by JustBashka** [comment]
> adding a new mod and it disappearing
I have re-downloaded Scarab after that and it was the new Scarab that didn't register it, that was what i was trying to communicate. Sorry for being unclear.

So, what is the intended use here when one updates Scarab through grabbing the newest release, which then doesn't register previously installed mods? Just "install" them again in the new Scarab? I have done so, because I needed to disable some mods and didn't know how to do that otherwise, and it appears to me that Scarab may have downloaded the mod files anew, even if it apparently threw them away in the end (judging this by for example looking at the CustomKnight mod, which appeared to have been downloading for a little while, but the modification times on the files in the directory are way older than yesterday).

Wouldn't it be pretty simple for Scarab to check the mod directories and to check for a version of the mod just like it presumably does when it reports a mod as outdated?

**Comment by fifty-six** [comment]
Installing a new version of the installer shouldn't clear installed mods, it's just that changing paths does. There's not really a way to get the version of a given mod from just the folders which is why if you change paths to something with them already in it won't do anything with them and treats it as a fresh install. Updating not keeping installed mods is very much a bug

**Comment by powerlord** [comment]
Whoops, I completely forgot about this issue.  In my case, I never validated that Hollow Knight was working before initially installed mods.  Hollow Knight basically wasn't working whether mods were enabled or not, so I used Steam to validate the install... which caused it to just ignore any installed mods.

Being someone with some IT experience I not only uninstalled Hollow Knight but also deleted all the leftover files before reinstalling Hollow Knight.

Since Scarab doesn't validate that mods actually exist, it was claiming that a bunch of mods were installed that were no longer present.
